### ISSUE TITLE
Hot corner partially disable dynamic workspaces

### ISSUE THREAD

**Issue by thalesmaoanz** [G-dH/custom-hot-corners-extended#100] opened 2024-05-10 22:44 UTC
Hi there, I just recently notice that using `GNOME Shell 43.9`with Custom Hot Corners - Extended 44.2 partially disabled the dynamic workspaces.

[Screencast from 2024-05-10 19-38-30.webm](https://github.com/G-dH/custom-hot-corners-extended/assets/165694443/09307def-5630-4407-9647-7b1a2a04d791)

**Comment by G-dH** [comment] 2024-05-10 23:43
Hi. Please, show me the list of all extensions enabled on your system, and find the other one, which causes this behavior.

**Comment by thalesmaoa** [comment] 2024-05-10 23:51
Sorry for not making myself clear. I did that. I've disabled each extension and did some test trying to find which one was responsible to suppress gnome dynamic workspace. It is the  Custom Hot Corners - Extended 44.2 the only one responsible for that.

Besides, I can't identify anything strange from the logs:

```
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:00 lenovo-debian gnome-shell[1548]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
mai 10 20:48:03 lenovo-debian gnome-shell[1548]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: O objeto não existe no caminho “/org/gnome/Terminal/SearchProvider”
mai 10 20:48:03 lenovo-debian gnome-shell[1548]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: O objeto não existe no caminho “/org/gnome/Terminal/SearchProvider”
```

**Comment by G-dH** [comment] 2024-05-11 00:20
Have you tried disabling all extensions except CHC-E?

**Comment by thalesmaoa** [comment] 2024-05-11 00:23
> Have you tried disabling all extensions except CHC-E?

Sure. I did! I have a fresh new Debian 12 bookworm.

**Comment by G-dH** [comment] 2024-05-11 00:41
Have you restarted the Shell after disabling all other extensions? I need to be certain it's a bug in CHC-E since I've never experienced this issue.

**Comment by thalesmaoa** [comment] 2024-05-11 01:26
Yes!

![image](https://github.com/G-dH/custom-hot-corners-extended/assets/14074573/f739aee8-bf70-4d14-8640-5d96a239a552)

After enabling hotcorner, I did reboot and the problem persist.
Maybe some debian old package. I have no idea how to even debug it.

**Comment by G-dH** [comment] 2024-05-11 01:32
Thanks, I'll look into it, when I have time.

**Comment by G-dH** [comment] 2024-05-11 07:32
I didn't notice on my small phone screen in the middle of the night, but you are comparing the window picker view with the applications view. That's how default GNOME Shell behaves, CHC-E has nothing to do with it. If you want consistent behavior of workspace thumbnails in both views, you can try my V-Shell extension.

**Comment by thalesmaoa** [comment] 2024-05-11 11:21
Hi @G-dH! I really thank you for your quick and fast reply. Hot corners is a must have extensions and I use it a lot. This is the main reason I can't understand why it is not working as expected. Although, it does work really well with Ubuntu distros (daily pop_os use and tested with Ubuntu).

I'm having a lot of trouble in order to explain the behavior because I can't print screen while mouse drag n drop. I will try with words now.

Sorry to insist and really appreciate your patience.

Since I have a small laptop screen, I use my gnome shell with multiple workspaces.

I drag my mouse to the left top corner and overview mode is activated.

![image](https://github.com/G-dH/custom-hot-corners-extended/assets/14074573/5e537b83-ac03-4b52-a17f-7955375d5656)

After that, I can click and drag windows back and forth. Either using the upper thumbnails or the bigger windows of the active workspace.

While doing this, you can place a window in between two workspaces and it will, automatically, create another workspace. I can't create a new workspace placing a new windows in between two workspaces with hot corners activated.

I will try to make new videos. I honestly think that I'm doing something wrong giving your feedback

**Comment by thalesmaoa** [comment] 2024-05-11 12:45
I can't reproduce it in a fresh new installation. I will dig it depper and close it for now. Thx

**Closed** 2024-05-11 12:46 UTC
Labels: invalid

**Comment by G-dH** [comment] 2024-05-11 19:23
Again, there is no bug affecting dynamic workspaces. You configured CHC-E to trigger the `Show/Toggle Overview - App Grid` instead of `Show/Toggle Overview - Window Picker`. In the app grid view, GNOME Shell hides workspace thumbnails and replaces them with scaled-down workspace previews from the window picker view, which doesn't support adding workspaces.
